# Generated by Django 6.0.6 on 2026-06-11 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='📦', max_length=10, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('url', models.URLField(blank=True, verbose_name='Сайт')),
                ('color', models.CharField(default='#666', max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название')),
                ('specs', models.TextField(blank=True, verbose_name='Характеристики')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='monitor.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Комплектующее',
                'verbose_name_plural': 'Комплектующие',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена, ₽')),
                ('scraped_at', models.DateTimeField(verbose_name='Дата')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='monitor.component', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Запись цены',
                'verbose_name_plural': 'История цен',
                'ordering': ['scraped_at'],
                'indexes': [models.Index(fields=['component', 'scraped_at'], name='monitor_pri_compone_06783c_idx'), models.Index(fields=['component', 'store'], name='monitor_pri_compone_d00db1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Целевая цена, ₽')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Уведомлён')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='monitor.component', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись в списке отслеживания',
                'verbose_name_plural': 'Список отслеживания',
                'unique_together': {('user', 'component')},
            },
        ),
    ]
